name = "dash"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "noir-personal"
database_id = "b8cd55bc-4360-4fad-92c2-0da3baf2d3b7"

[vars]
BIO_URL = "https://bio.noirnotfun.workers.dev"
RAW_URL = "https://raw.noirnotfun.workers.dev"
